### ISSUE TITLE
cant install it in the steam folder

### ISSUE THREAD

**Issue by engjn** [ManlyMarco/VRK-HF_Patch#10]
Hello,
i downloaded the VR Kanojo HF Patch v1.1.exe
if i want it to get installed in the steamapps->common->Kanojo folder it says: Files were not found in selected directory. This Patch has to be installed directly to the main game directory in order to work properly. 
After being sure that this IS the right folder i press on next and it tells me:
ERROR - Critical game files are missing. make sure this is the game directory. if the directory is correct you have to reinstall the game.
i reinstalled the game like 4,5 times and tried my other disk but nothing is working. can someone help?

**Comment by ManlyMarco** [comment]
You are using the full game not the benchmark, right?

**Comment by ThatThing04** [comment]
I'm having the same issue, I've downloaded the game twice on steam and the patch 3 times, and nothing works.

**Comment by ManlyMarco** [comment]
I can't reproduce the issue, the patch works fine with a fresh steam install of the game. Make sure you are pointing the patch to the correct directory.
