### ISSUE TITLE
Missing swimsuit texture on non-Steam version

### ISSUE THREAD

**Issue by ayyy7392064** [ManlyMarco/VRK-HF_Patch#2]
Hello,
first of all I can confirm that this patch also works well on the non-Steam version of the game (the one you can officially buy from [here](http://www.illusiondlshop.com/products/detail.php?product_id=5)).
The only issue I found (so far) is that the swimsuit model appears as a magenta blob instead of the correct texture (which was there before installing the patch).
How can I troubleshoot this problem? I guess some modded assets files do not contain this texture?

Title screen version is 1.07.
Patch installation done with all default settings, no changes.

Thank you

**Comment by ayyy7392064** [comment]
Did some tests, the culprit is the default female uncensor (cyberbeing's uncensors work fine).

Where can I find the sources for the default uncensored model? I couldn't find them in the repository, and there doesn't seem to be a link in the patch manual.

**Comment by ManlyMarco** [comment]
There are no source files for the uncensors, they were made with SB3U as they are now. I suggest checking some basic SB3U tutorials for modding KK, it's not hard if you follow the basic item porting guide.
https://github.com/xm007/Koikatsu-Modding

**Comment by ayyy7392064** [comment]
Thank you for the pointer, that was really helpful!

So I dived in and found all needed modifications (remove mosaic, change model and texture), applied them on the latest asset files (v1.07) and got the uncensor successfully working, including the swimsuit texture!

Would you like to add these updated files to the HF_Patch collection? How do you prefer for me to send you the modded files?

And I've really got to say, SB3UGS is such a good piece of software, kudos to the developers!

**Comment by ManlyMarco** [comment]
Assuming that the new uncensor works on the steam version as well then I'll gladly add it to the patch.
It would be ideal if we could talk on discord, you can join the general server for these games here https://discord.gg/illusionsoft
You can DM me or ping me in the modding channel then. I'll probably need some pointers on how to test it properly.

**Comment by ManlyMarco** [comment]
Solved in v1.1
