### ISSUE TITLE
Cant Unlock all "Sexy Lessons"

### ISSUE THREAD

**Issue by ZanyISP** [ManlyMarco/VRK-HF_Patch#3]
You cant Unlock any of the "Sexy Lessons" after Doggy Style For some reason.

**Update! It Worked after I restarted the game. The only thing I did was add [These Files from 18+ Upgrade Patch](https://www.reddit.com/r/SteamUncensored/comments/8bbd7w/vr_kanojo/)
`Alternative patch [a 3D model instead of a 2D texture] Files`

**Comment by ManlyMarco** [comment]
Are you sure it was a problem with the patch and not the game itself? That's the first time I hear about this.

**Comment by ManlyMarco** [comment]
Seems to work fine on a fresh game install + the patch.
