### ISSUE TITLE
HF Patch Wizard can't find VR Kanojo files inside VR Kanojo Game folder

### ISSUE THREAD

**Issue by salifrumen** [ManlyMarco/VRK-HF_Patch#8]
Hi there,
I have downloaded the steam version of KanojoBenchmarkVR on my D: drive. Steam tells me, my "VRBenchMarkKanojo"-folder is at "D:\Programme\Steam\steamapps\common\VRBenchMarkKanojo". Inside is a "VRBenchMarkKanojo.exe", an "abdata"-Folder, "localization"-folder, "version.txt" and a "VRBenchMarkKanojo_Data"-folder. If I tell the wizard to try to install your patch into this folder, he asks, if I really want to continue, because there are no VR Kanojo files in this folder and then after that tells me, that critical files are missing.

Do you know how to fix this? Has it to do with the fact, that in your Readme you say, that I have to search for a "VR Kanojo.exe"? I have already tried to rename it to "VR Kanojo.exe" but the error remained.
So far I only managed to make the wizard bypass the first error message but still get stuck at the second error message by renaming "VRBenchMarkKanojo_Data" to "VR_Kanojo_Data".

**Comment by ManlyMarco** [comment]
This is not the full game, it's a trial version. The patch only works on the full game.
