### ISSUE TITLE
VRK Launch Failed and Immediately Exit

### ISSUE THREAD

**Issue by Tomahawkd** [ManlyMarco/VRK-HF_Patch#9]
VRK constantly crashes several seconds after I launch it both in Steam VR mode and Oculus VR mode with/without the patch. Here is the log screenshot produced by developer version of BepInEx. What can I do to fix this? Many thanks.
System: Windows 11
DirectX: 12
Video Card: Nividia 4090 with driver version 526.86
VR: Oculus Quest 2

![Screenshot 2022-11-27 002252](https://user-images.githubusercontent.com/20868632/204098981-1fcbfa9f-fe42-4176-b6a4-6031ee0dd13a.png)

**Comment by ManlyMarco** [comment]
Nothing wrong in the log here. If it crashes even without the patch then try making a fresh install. You can search in steam discussions for similar cases if that doesn't help.

**Comment by Tomahawkd** [comment]
I'll check them out. Many thanks.
